import { FreshContext } from "$fresh/server.ts";
const products = [
    {
        name: "Product 1",
        image: "https://via.placeholder.com/150",
        price: 100,
        discount: 10,
        finalPrice: 90,
        category: "Category 1",
        description: "Description 1",
        id: 1,
        quantity: 10,
        size: "Size 1",
        color: "Color 1",
        material: "Material 1",
        brand: "Brand 1",
        model: "Model 1",
        weight: 1,
        width: 1,
        height: 1,
        depth: 1,
        diameter: 1,
        capacity: 1,
        power: 1,
        voltage: 1,
        frequency: 1,
        warranty: 1,
        origin: "Origin 1",
        stock: 10,
        status: "Status 1",
        createdAt: "2021-09-01T00:00:00Z",
        updatedAt: "2021-09-01T00:00:00Z",
        deletedAt: "2021-09-01T00:00:00Z",
    },
    {
        name: "Product 2",
        image: "https://via.placeholder.com/150",
        price: 200,
        discount: 20,
        finalPrice: 180,
        category: "Category 2",
        description: "Description 2",
        id: 2,
        quantity: 20,
        size: "Size 2",
        color: "Color 2",
        material: "Material 2",
        brand: "Brand 2",
        model: "Model 2",
        weight: 2,
        width: 2,
        height: 2,
        depth: 2,
        diameter: 2,
        capacity: 2,
        power: 2,
        voltage: 2,
        frequency: 2,
        warranty: 2,
        origin: "Origin 2",
        stock: 20,
        status: "Status 2",
        createdAt: "2021-09-02T00:00:00Z",
        updatedAt: "2021-09-02T00:00:00Z",
        deletedAt: "2021-09-02T00:00:00Z",
    },
];

export const handler = (_req: Request, _ctx: FreshContext): Response => {
    const randomIndex = Math.floor(Math.random() * products.length);
    const productsData = JSON.stringify(products[randomIndex]);
    return new Response(productsData);
};
